### ISSUE TITLE
Requirement

### ISSUE THREAD

**Issue by plinioMoreno** [vislab-tecnico-lisboa/vizzy_control#1]
These controllers should act like the yarp ones. So my question is: How are you going to implement the version-vergence controller?

**Comment by ruipimentelfigueiredo** [comment]
@plinioMoreno I was thinking about two possibilities: 
The first could be changing the source code of the original yarp plugins and change the interfaces to ROS. The second would be to use the standard  and out-of-the-box PID ros controllers just to expose the simulated motors to the ROS side. Then the version-vergence controller would be a higher layer using the standard PID controllers. What do you think?

**Comment by plinioMoreno** [comment]
Actually this hasn't been done yet in the plugins. @mikearagao is 
working on that. The second option is the best one, because we want the 
controllers totally independent.

On 2/8/2015 1:03 PM, Rui Miguel Horta Pimentel de Figueiredo wrote:
>
> @plinioMoreno <https://github.com/plinioMoreno> I was thinking about 
> two possibilities:
> The first could be changing the source code of the original yarp 
> plugins and change the interfaces to ROS. The second would be to use 
> the standard and out-of-the-box PID ros controllers just to expose the 
> simulated motors to the ROS side. Then the version-vergence controller 
> would be a higher layer using the standard PID controllers. What do 
> you think?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vislab-tecnico-lisboa/vizzy_control/issues/1#issuecomment-73409901>.
>

-- 
___________________

Plinio Moreno López
http://www.isr.ist.utl.pt/~plinio
plinio@isr.tecnico.ulisboa.pt
___________________

**Comment by ruipimentelfigueiredo** [comment]
Ok, the controllers are now working for the head and torso on the ROS side. It's now possible to move the joints in gazebo using ROS

**Comment by mikearagao** [comment]
Nice @ruipimentelfigueiredo :smile:

Yeah I think that is the best option. This way we'll have two separate approaches (hopefully!)...
